repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      # run isort from project pipenv to fix third party detection
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        args: ["--profile", "black"]
        types: [python]
