repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.30.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "6.0"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.21.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: [--ignore-words-list, "groupin"]

  - repo: https://github.com/python-poetry/poetry
    rev: 2.3.4
    hooks:
      - id: poetry-check

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        stages: [pre-commit]
        language: system
        entry: poetry run ruff check
        args: [--fix, --unsafe-fixes]
        types: [python]

      - id: ruff-format
        name: ruff-format
        stages: [pre-commit]
        language: system
        entry: poetry run ruff format
        types: [python]
