version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - asdf plugin add poetry
    - asdf install poetry latest
    - asdf global poetry latest
    - poetry install --extras docs
    - poetry run python -m sphinx -b html -d docs/_build/doctrees docs $READTHEDOCS_OUTPUT/html

formats: all
