sudo: false
language: python
python:
  - 3.7
  - 3.8
  - 3.9

install:
  - pip install tox tox-travis
  - pip install coverage coveralls

script:
  - tox -r

after_success:
  - coverage report
  - coveralls
