[tool.poetry]
name = "django-permission2"
version = "2.0.0-beta.6"
description = "A simple permission system which enable logical permission systems in Django"
authors = ["Malte Gerth <mail@malte-gerth.de>"]
license = "MIT"
readme = "README.rst"
homepage = "https://django-permission2.readthedocs.io/en/latest/"
documentation = "https://django-permission2.readthedocs.io/en/latest/"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
keywords = ["django","object","logical","permission"]
packages = [
    { include = "permission", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
app_version = "^1.0.1"
django-appconf = "^1.0.5"
Sphinx = {version = "5.1.1", optional = true}
sphinx-rtd-theme = {version = "1.0.0", optional = true}

[tool.poetry.dev-dependencies]
Django = "3.2.15"
tox = "3.25.1"
coverage = "6.4.3"

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
