[tox]
isolated_build = true
envlist =
    py{310,311,312}-django{42}
    py{310,311,312}-django{50}
    py{310,311,312,313}-django{51}
    py{310,311,312,313}-django{52}
    py{312,313,314}-django{60}
    docs

[testenv]
deps =
    django42: Django~=4.2.0
    django50: Django~=5.0.0
    django51: Django~=5.1.0
    django52: Django~=5.2.0
    django60: Django~=6.0

constrain_package_deps = true
use_frozen_constraints = false

commands =
    # echo python version for debugging
    python --version
    # echo django version for debugging
    django-admin --version
    python ./manage.py test tests {posargs}

[testenv:docs]
basepython=python

changedir=docs

dependency_groups = docs

commands=
    make clean
    make html

allowlist_externals=
    make

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
